name: Swift

on: [push, pull_request]

jobs:
  build-ios:
    name: Test on iOS
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    runs-on: macOS-11 # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    strategy:
      matrix:
        destination: ['OS=15.2,name=iPhone 13 Pro', 'OS=14.4,name=iPhone 8']
    steps:
    - uses: actions/checkout@v2
    - name: Link to 14.4 Simulators
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        ls /Applications/Xcode*
        sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.4.simruntime
        ls /Library/Developer/CoreSimulator/Profiles/Runtimes
        xcrun simctl list devicetypes runtimes
        xcrun simctl list devices 14.4
    - name: Build
      run: xcodebuild test -destination '${{ matrix.destination }}' -scheme 'AppFoundation-Package'
    - name: Run tests
      run: xcodebuild test -destination '${{ matrix.destination }}' -scheme 'AppFoundation-Package'

